### ISSUE TITLE
Categorical.apply_nonreduce doesn't handle filtered categoricals correctly.

### ISSUE THREAD

**Issue by ryan-gunderson** [rtosholdings/riptable#170]
```
d = np.arange(10) % 3
c = rt.Cat(d, filter=(d!=0))
x = np.ones(10)
c.apply_nonreduce(np.cumsum, x)
```
gives
```
*gb_key_0   col_0
---------   -----
Filtered     1.00
1            1.00
2            2.00
Filtered     3.00
1            2.00
2            4.00
Filtered     5.00
1            3.00
2            6.00
Filtered     7.00
```
suggesting that it is grouping the filtered group with the last unfiltered group.  The correct result should be
```
*gb_key_0   col_0
---------   -----
Filtered     1.00
1            1.00
2            1.00
Filtered     2.00
1            2.00
2            2.00
Filtered     3.00
1            3.00
2            3.00
Filtered     4.00
```

**Comment by OrestZborowski-SIG** [comment]
The first thing that `cat.apply()` does is get a "clean" version of itself using `self.filter(None)`. The intention is to remove unused bins from its uniques beforehand.
`self.filter(None)` in this case calls `self.grouping.regroup(filter=None, ikey=self._fa)` to regroup itself, given the index array.
`self.grouping.regroup()` computes the same set of keys (since no filter). and since the number of uniques is unchanged, "fixes up the new ikey to match old ordering" using the code
```
ikey_fix = self.ikey[ifirstkey][ikey_new-1]
```
Now since the categorical was filtered, the initial `ikey` looks something like `[1, 0, ...]` where the 0 bins are "filtered". Since `ikey_new` is the same as `ikey`, the result of `ikey_new-1` is `[0, -1, ...]` which uses in some wraparound indexing, and ends up with an array where all of the indices are no longer 0. The resulting new categorical no longer retains the filtered entries.
