### ISSUE TITLE
Dataset.from_pandas() does not handle unicode strings properly

### ISSUE THREAD

**Issue by OrestZborowski-SIG** [rtosholdings/riptable#213]
```
import riptable as rt
import pandas as pd

df = pd.DataFrame()
df.loc[0,'Name'] = 'Namé'

rt.Dataset.from_pandas(df) # Exception thrown
```
throws exception:
```
Exception has occurred: UnicodeEncodeError
'ascii' codec can't encode character '\xe9' in position 3: ordinal not in range(128)
```

**Comment by zhangyingmath** [comment]
Yes, I remember running into a similar error. Curiously, this works: rt.Dataset(df)

Since I have told my colleagues before that they should switch from calling rt.Dataset(df) into rt.Dataset.from_pandas(df), (since there are other cases where rt.Dataset.from_pandas does better, if I remember correctly), it would be good to fix the bug as you reported. Thanks!
