### ISSUE TITLE
rt.FA == uint64 fails on Linux (not Windows)

### ISSUE THREAD

**Issue by OrestZborowski-SIG** [rtosholdings/riptable#233]
Running the following
```
import riptable as rt
import numpy as np

uval = 13786081686375571456

na = np.array([uval], dtype=np.uint64)
print(f"na = {na.__repr__()}")

x = na==uval
print(f"na==uval = {x}")

fa = rt.FA([uval], dtype=np.uint64)
print(f"fa = {fa.__repr__()}")

x = fa==uval
print(f"fa==uval = {x}")
```

On Windows:
```
na = array([13786081686375571456], dtype=uint64)
na==uval = [ True]
fa = FastArray([13786081686375571456], dtype=uint64)
fa==uval = [ True]
```

while on Linux:
```
na = array([13786081686375571456], dtype=uint64)
na==uval = [ True]
fa = FastArray([13786081686375571456], dtype=uint64)
fa==uval = [False]
```

**Comment by staffantj** [comment]
This feels as if it may have something to do with the differing dtypes for 64-bit between linux and windows. I'm not convinced that the macro'd case statements for these are used correctly everywhere.

**Comment by RCMcNamara** [comment]
So the fastarray __eq__ method passes super().__eq__ to _compare_check. Now unless you are dealing with a str type which riptable wants as a bit string, this just calls super().__eq__(other) where other is the thing you want to check equality against. Now I thought that would just switch over to the numpy implementation (because super()) but actually looking at it with the debugger that calls __array_ufunc__ which, after doing a lot of complicated checks, passes MATH_OPERATIONS.CMP_EQ to MathLedger in rt_ledger. It might be worth having a comment that mentions this behavior. 

Anyway, that calls rc.BasicMathTwoInputs which I suspect eventually calls GetComparisonOpFast in Compare.cpp. Now that splits into cases. On line 1055, if the input has type int64 and the input types are different, it calls COMP_EQ_uint64_t. On line 1096, oddly enough, when dealing with a uint164 (and the types of the inputs disagree), now it calls COMP_EQ. I think these probably are both mistakes, and especially the second one. Compare that to the calls on lines 1100, 1102, 1104 and 1106 to COMP_GT_uint64_t, COMP_GE_uint64_t, COMP_LT_uint64_t and COMP_LE_uint64_t.

Unfortunately, I don't have it set up to compile the C++ code locally so I can't test this solution but I suspect that these problems (this one and the similar one Sheridan was having) could be fixed by implementing the following solutions:

1. Change COMP_EQ on line 1096 to COMP_EQ_uint64_t
2. Change CMP_NE on line 1098 to COMP_NE_uint64_t

Now it would make sense to propose changes like these

3. Change COMP_EQ_uint64_t on line 1055 to COMP_EQ_int64_t
4. Change COMP_NE_uint64_ton line 1055 to COMP_NE_int64_t

**EXCEPT** that these functions don't exist in the riptide C++. Now they could be added relatively easily I think. Looking at the code in Compare.cpp around line 333, you would add something like 

template <typename T>
FORCE_INLINE const bool COMP_EQ_int64_t(T X, T Y)
{
    if ((X | Y) & 0x8000000000000000)
        return false;
    return (X = Y);
}

template <typename T>
FORCE_INLINE const bool COMP_NE_int64_t(T X, T Y)
{
    if ((X | Y) & 0x8000000000000000)
        return false;
    return (X != Y);
}

I believe this was probably intended if you read the C++ comments but I am really not a C++ programmer so I would appreciate it someone else could double check that this makes sense. Thanks

**Comment by RCMcNamara** [comment]
Not sure why it won't let me edit my comment but all the instances of COMP should be CMP

**Comment by OrestZborowski-SIG** [comment]
The problem underlying this issue was due to a bad uint64 comparison under Linux.
I will take a closer look at your comment re. other issues, thanks.
