### ISSUE TITLE
Groupby changes type

### ISSUE THREAD

**Issue by seignour** [rtosholdings/riptable#48]
It seems that groupby changes the type of categoricals back to strings, as here:

ds = rt.Dataset(dict(trader=['a', 'a', 'b', 'b', 'c', 'c'], shares=np.arange(6)))
ds.trader = rt.Categorical(ds.trader)
gds = ds.trader.sum(ds.shares)
print(ds.trader.dtype)
print(gds.trader.dtype)
int8
|S1

I get the same result if I do the groupby using the alternate approach/syntax:
gds = ds.gb('trader').shares.sum()

**Comment by tdimitri** [comment]
If i change it to..

ds = rt.Dataset(dict(trader=['a', 'a', 'b', 'b', 'c', 'c'], shares=np.arange(6)))
trader = rt.Categorical(ds.trader)
gds = trader.sum(ds.shares)
print(ds.trader.dtype)
print(gds.trader.dtype)

you will notice that plain 'trader' (as opposed to ds.trader) is a Categorical, then trader.sum(ds.shares) return a Dataset (perhpas the issue?).  Then gds[0] is the FastArray that I think you want.

**Comment by ryan-gunderson** [comment]
```
tmp = rt.Dataset({'A':rt.Cat(['A','B','C'])})
tmp.A.null().A # This is a string, not a cat.
```

**Comment by tdimitri** [comment]
We want gds.trader to remain a categorical.   gds.trader = Cat(gds.trader, arange(len(gds.trader)+1))  <- as last step when making the dataset.

The same categorical  gds.trader = ds.trader  should also be considered.

**Comment by tdimitri** [comment]
Ah, it sounds like I misunderstood how miltikey cats are implemented.  In that case, yes, I agree that there is no efficient way to do that.

It doesn’t seem that there would be a way to do that without tracking how things were incrementally reduced and that seems like it will open up a whole other mess of an API to try to specify exactly how far back you transform.

---

I think what you want is a double transform=True…
The second reduction could have a transform=True, which could transform back to the first reduction which could transform back to the original Dataset.

That I have to think about a little how to do this.  Feels like need a special chain command…

my_cat.nansum(my_column, xtransform=True)
red.cat(‘Exp’).nanmean(red[0], transform=True)

The first command produces the transform key back as an additional column.
The second one realizes the transform is a double transform.

---
Multikey cats do not have the uniques for the individual keys.  It calculates them by fusing together all the keys and reading them as one key.

Put another way, it actually does the same thing as going from multiple arrays to a recordarray, then hashing that.  Unless you are in lexsort mode, and then that is a whole nother process.

Which is why I know we can speed up the reverse… recordarray to multiple arrays.

---
Because I do two reduction.  
•	On the first reduction (nansum), transform works to align to `red` to `data`.
•	On the second reduction (nanmean), transform works to align `final` to `red`.
There isn’t a transformation that aligns `final` to `data`.

So I suppose this comes down to how multi-key cats work.  I am led to believe that a multikey categorical has two internal lists of categories for the two keys.  Then categories of the multikey categorical is a list of 2-tuples if integers.  Then the underlying numpy array is an array of integers which dereference to an array of 2-tuples of integers which could then deference to an array of 2-tuples of strings (or whatever the underlying dtypes of the two cats are).

During the reduction, you could, at minimum, choose not throw away the uniques of the 2 component cats.  Furthermore you have the ikeys for the two cats by just taking the first and second components of the list of 2-tuples of integers you hold for the categories of the multikey cat.

One thing that you would need to compute is the grouping data (igroup) for the two new cats if needed.

Is this picture correct?
cat1 = [a, b, a, a] -> [1,2,1,1] + [filtered, a, b]
cat2 = [x, x, y, y] -> [1,1,2,2] + [filtered, x, y]
multicat = [(a,x), (b,x), (a,y), (a,y)] -> [1,2,3,3] + [filtered, (1,1), (2,1), (1,2)]

So having the multicat you can build the single cats in a single (non-hashing) pass.

---
>> And this cannot be done with transform because you have two reductions.
I don’t understand this comment.

Also after 
red = my_cat.nansum(my_column)

Well red has one result per unique group.
So then you want to do…
red.cat(‘Exp’).nanmean(red.my_column)   or  red.cat(‘Exp’).nanmean(red[0])

Ok yeah, that is the fastest way to regroup on ‘Exp’ after the reduction.  A multikey categorical is not going to help… worse really as the two keys: ‘Sym’ and ‘Exp’ are fused together and have to be decoupled.
So in this case, it would take longer if the result of the reduction made a Categorical.

What about every time I don’t want a Categorical… and I am making it anyway?

So then maybe it boils down to chaining…
my_cat.nansum(my_column).Exp.nanmean(ooops nothing to put in here)

So then back to two lines…
I can make a helper function in a FastArray to make a Categorical… for instance .cat function.
red = my_cat.nansum(my_column)
red.Exp.cat().nanmean(red[0]) … but this is not really much better than red.cat(‘Exp’).nanmean(red[0])
vs. red.Exp.nanmean(red[0]) which would be your suggestion..

Now we are down to typing “.Exp.”  instead of “.cat(‘Exp’). “ but the cost is that we always create a categorical whether or not someone wants to use it just for those extra key strokes?
So I still don’t really see it.

--
my_cat = data.cat([‘Sym’, ‘Exp])
red = my_cat.nansum(my_column)

Now do I do:

cat2 = red.cat([‘Exp’])
final = cat2.nanmean(red.my_coulumn)

or

final = red.Exp.nanmean(red.my_column)

If the key columns in the reduction are arrays I have to make the categorical by hand again.  If they are cats by default, I don’t.

Now, if I want to merge the final data back to the starting data, everything needs to get hashed again if they don’t stay as cats.  And this cannot be done with transform because you have two reductions.
